### 1. `promise对象`
`promise`类似于java中的`future`对象， 包含3种状态: `pending, fulfilled, rejected`, 状态之间的转化是不可逆的，  状态本身是私有变量，不能直接访问，只能通过`resolve(), rejected()`函数改变状态。也就是说， `Promise`对象是对某种不确定状态的抽象,  可以用来描述IO操作、网络请求等预期不确定的结果。

```javascript
//  这个 promise对象的状态是pending
var p = new Promise(() => {} 

// 这个promise对象初始状态是pending, 3秒钟之后状态变为fulfilled, 结果值为100
var p = new Promise((resolve) => setTimeout(resolve, 3000, 100)) 

// 这个promise对象初始状态是pending, 3秒之后变为rejected, 如果后续没有catch操作会抛出异常
var p = new Promise(resolve, reject) => setTimeout(reject, 3000, 123)) 

// 当p变为rejected状态时会执行括号内的函数，将error打印出来，就不会抛出异常
p.catch(e => console.log) 
```

### 2. `async/await`
- `async`可以仅仅理解为一个标识符， 提示这段代码有异步操作，`async`本真并不能导致异步执行，关键要看`await`

- `await` 代码执行到`await`时会提交一个任务到任务队列，不再继续执行`await`后面的代码，主流程执行完毕之后，当`await`右侧得到一个结果时，恢复执行，如果结果是`rejected`,  将直接返回.  `await`必须放置到`async`函数里
```javascript
// 这个promise对象初始状态是pending, 3秒钟之后状态变为fulfilled, 结果值为100
var p = new Promise((resolve) => setTimeout(resolve, 3000, 100)) 

async get(){
	var x = await p; //   等待p得到结果
	console.log(p);
}

//  3秒钟之后打印100
get()
```

```javascript
async function get(){
	var x = await Promise.reject('o huo'); //  得到了一个rejected的结果，下面的代码不会继续执行
	console.log(x);  //  不会被执行
}

//  1.会抛出Uncatched  错误
get()

//  2.打印出'o huo'
get().catch(err => console.log(err))

// 3. 打印出'o huo',  等价于上面的写法
get().then(null, err=>console.log(err))

// 4.try catch并不能捕获reject
try{
	get()
}catch(e){
	console.log(e) 
}
```

```javascript
async function get(){
	var x = await Promise.resolve(new Error('o huo')); //  得到了一个resolve的结果
	console.log(x);  
	throw x;
}

// get()函数中的console.log(x)正常执行，但是throw的Error不能被try catch
try{get()}catch(e){console.log(e)}

// get()函数中throw的Error只能通过promise的then/catch来处理
get().catch(console.log)
```

即使`await`后面的结果是确定的(例如`var x = await 3`),  依然会按照异步执行的方式执行。

